[package]
name = "altc"
version = "0.1.0"
edition = "2021"
default-run = "schemagen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "altc"
required-features = ["bin"]

[[bin]]
name = "schemagen"
required-features = ["schemagen"]

[features]
default = ["bin"]
bin = ["clap"]
schemagen = ["clap", "syn", "quote"]

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"] }
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
wasm-bindgen = "0.2.92"
serde_with = "3.7.0"
# bin stuff
clap = { version = "4.5.4", features = ["derive"] , optional = true }
# schemagen stuff
syn = { version = "2.0", optional = true }
quote = { version = "1.0", optional = true }