[package]
name = "altc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "altc"
required-features = ["bin"]

[features]
default = ["bin"]
bin = ["clap"]

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"] }
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
clap = { version = "4.5.4", features = ["derive"] , optional = true }
