name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  BUILD_ARGS: "--bin altc --release --features bin --target-dir ./build"

jobs:
  build:
      name: Build - ${{ matrix.platform.name }}
      # By default, runs on Ubuntu, otherwise, override with the desired os
      runs-on: ${{ matrix.platform.os || 'ubuntu-latest' }}
      strategy:
        matrix:
          platform:
            # Linux
            - name: Linux x86_64
              target: x86_64-unknown-linux-gnu
            - name: Linux aarch64
              target: aarch64-unknown-linux-gnu
              use-cross: true
  
            # Mac OS
            - name: MacOS x86_64
              os: macos-latest
              target: x86_64-apple-darwin
            - name: MacOS aarch64
              os: macos-latest
              target: aarch64-apple-darwin

            # Windows
            - name: Windows x86_64
              # Use another GitHub action OS
              os: windows-latest
              target: x86_64-pc-windows-msvc
      steps:
        - uses: actions/checkout@v3
        - name: Set up cargo cache
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ matrix.platform.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        - name: Install ${{ matrix.platform.target }} Toolchain
          run: rustup target add ${{ matrix.platform.target }}
        - name: Run tests
          run: cargo test --verbose
        - name: Build ${{ matrix.platform.name }} binary
          uses: actions-rs/cargo@v1
          with:
            command: build
            use-cross: ${{ matrix.platform.use-cross }}
            args: ${{ env.BUILD_ARGS }} --target ${{ matrix.platform.target }}
        - name: Upload ${{ matrix.platform.name }} binary
          uses: actions/upload-artifact@v2
          with:
            name: altc.${{ matrix.platform.target }}
            path: target/${{ matrix.platform.target }}/release/altc
        
      
    
